### ISSUE TITLE
Getting "bash: [: too many arguments" under Bash on WSL

### ISSUE THREAD

**Issue by serpro69** [yedhink/bashed-on-a-feeling#2]
Hi,

Trying to use your script on bash under Windows Subsystem for Linux and getting the following error  "bash: [: too many arguments" when executing bash commands.

Thought I messed up the installation, but full clean reinstall did not help.

Any ideas what might be the cause?

**Comment by yedhink** [comment]
im not sure whether this fix would do the trick. honestly i'm not that familiar with windows. Just  try and use the fix and reinstall. see if it works

**Comment by serpro69** [comment]
@yedhink seems to have fixed it. Thanks for the nice prompt!
