### ISSUE TITLE
debian stretch: local repos print error message

### ISSUE THREAD

**Issue by karlredman** [yedhink/bashed-on-a-feeling#3]
Hi, nice job. 

On my system I get the following error message output when working in a local (non remote) repository:
```
fatal: ambiguous argument 'origin/master..': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

The problem stems from an unchecked `git diff --stat origin/master` in the case where origin has not been set (i.e. no remote exists). I have a pull request ready though and will submit it here in a bit.

**Comment by yedhink** [comment]
this was a good issue.
